# -*- coding: utf-8 -*-
"""DSP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0utdhyBHtobf30-6jvW5zD9qMJeJ0qj

# Convolution of two finite length signals
"""

from scipy import signal
import numpy as np
x=np.array([3,2,1])
h=np.array([3,1,2])
y=signal.convolve(x,h)
print(y)

